print("Lista de Exercícios - Estruturas de Controle")
print(" ")
print("Exercício 5")
c1, c2, c3, c4, c5  = [int(x) for x in input("Por favor insira cinco números inteiros separados por vírgula: ").split(",")]
ca1 = (c1 - 1)
cs1 = (c1 + 1)
ca2 = (c2 - 1)
cs2 = (c2 + 1)
ca3 = (c3 - 1)
cs3 = (c3 + 1)
ca4 = (c4 - 1)
cs4 = (c4 + 1)
ca5 = (c5 - 1)
cs5 = (c5 + 1)
print("O primeiro número é {} e seu antecessor é {} e seu sucessor é {}".format(c1,ca1,cs1))
print("O segundo número é {} e seu antecessor é {} e seu sucessor é {}".format(c2,ca2,cs2))
print("O terceiro número é {} e seu antecessor é {} e seu sucessor é {}".format(c3,ca3,cs3))
print("O quarto número é {} e seu antecessor é {} e seu sucessor é {}".format(c4,ca4,cs4))
print("O quinto número é {} e seu antecessor é {} e seu sucessor é {}".format(c5,ca5,cs5))
print(" ")
